// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request for [ApplyParameters][google.cloud.memcache.v1.CloudMemcache.ApplyParameters].
///
/// [google.cloud.memcache.v1.CloudMemcache.ApplyParameters]: <doc:CloudMemcacheClient/applyParameters(request:options:)>
public struct ApplyParametersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of the Memcached instance for which parameter group updates
  /// should be applied.
  public var name: Swift.String = Swift.String()

  /// Nodes to which the instance-level parameter group is applied.
  public var nodeIds: [Swift.String] = []

  /// Whether to apply instance-level parameter group to all nodes. If set to
  /// true, users are restricted from specifying individual nodes, and
  /// `ApplyParameters` updates all nodes within the instance.
  public var applyAll: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ApplyParametersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApplyParametersRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memcache.v1.ApplyParametersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
