// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A Memorystore for Memcached instance
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Unique name of the resource in this scope including project and
  /// location using the form:
  ///     `projects/{project_id}/locations/{location_id}/instances/{instance_id}`
  ///
  /// Note: Memcached instances are managed and addressed at the regional level
  /// so `location_id` here refers to a Google Cloud region; however, users may
  /// choose which zones Memcached nodes should be provisioned in within an
  /// instance. Refer to [zones][google.cloud.memcache.v1.Instance.zones] field for more details.
  ///
  /// [google.cloud.memcache.v1.Instance.zones]: <doc:Instance/zones>
  public var name: Swift.String = Swift.String()

  /// User provided name for the instance, which is only used for display
  /// purposes. Cannot be more than 80 characters.
  public var displayName: Swift.String = Swift.String()

  /// Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// The full name of the Google Compute Engine
  /// [network](/compute/docs/networks-and-firewalls#networks) to which the
  /// instance is connected. If left unspecified, the `default` network
  /// will be used.
  public var authorizedNetwork: Swift.String = Swift.String()

  /// Zones in which Memcached nodes should be provisioned.
  /// Memcached nodes will be equally distributed across these zones. If not
  /// provided, the service will by default create nodes in all zones in the
  /// region for the instance.
  public var zones: [Swift.String] = []

  /// Required. Number of nodes in the Memcached instance.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Required. Configuration for Memcached nodes.
  public var nodeConfig: Instance.NodeConfig? = nil

  /// The major version of Memcached software.
  /// If not provided, latest supported version will be used. Currently the
  /// latest supported major version is `MEMCACHE_1_5`.
  /// The minor version will be automatically determined by our system based on
  /// the latest supported minor version.
  public var memcacheVersion: MemcacheVersion = MemcacheVersion()

  /// User defined parameters to apply to the memcached process
  /// on each node.
  public var parameters: MemcacheParameters? = nil

  /// Output only. List of Memcached nodes.
  /// Refer to [Node][google.cloud.memcache.v1.Instance.Node] message for more details.
  ///
  /// [google.cloud.memcache.v1.Instance.Node]: <doc:Instance/Node>
  public var memcacheNodes: [Instance.Node] = []

  /// Output only. The time the instance was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time the instance was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The state of this Memcached instance.
  public var state: Instance.State = Instance.State()

  /// Output only. The full version of memcached server running on this instance.
  /// System automatically determines the full memcached version for an instance
  /// based on the input MemcacheVersion.
  /// The full version format will be "memcached-1.5.16".
  public var memcacheFullVersion: Swift.String = Swift.String()

  /// List of messages that describe the current state of the Memcached instance.
  public var instanceMessages: [Instance.InstanceMessage] = []

  /// Output only. Endpoint for the Discovery API.
  public var discoveryEndpoint: Swift.String = Swift.String()

  /// The maintenance policy for the instance. If not provided,
  /// the maintenance event will be performed based on Memorystore
  /// internal rollout schedule.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. Published maintenance schedule.
  public var maintenanceSchedule: MaintenanceSchedule? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let labels = CodingKeys(stringValue: "labels")
    static let authorizedNetwork = CodingKeys(stringValue: "authorizedNetwork")
    static let zones = CodingKeys(stringValue: "zones")
    static let nodeCount = CodingKeys(stringValue: "nodeCount")
    static let nodeConfig = CodingKeys(stringValue: "nodeConfig")
    static let memcacheVersion = CodingKeys(stringValue: "memcacheVersion")
    static let parameters = CodingKeys(stringValue: "parameters")
    static let memcacheNodes = CodingKeys(stringValue: "memcacheNodes")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let state = CodingKeys(stringValue: "state")
    static let memcacheFullVersion = CodingKeys(stringValue: "memcacheFullVersion")
    static let instanceMessages = CodingKeys(stringValue: "instanceMessages")
    static let discoveryEndpoint = CodingKeys(stringValue: "discoveryEndpoint")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let maintenanceSchedule = CodingKeys(stringValue: "maintenanceSchedule")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "labels",
      "authorizedNetwork",
      "zones",
      "nodeCount",
      "nodeConfig",
      "memcacheVersion",
      "parameters",
      "memcacheNodes",
      "createTime",
      "updateTime",
      "state",
      "memcacheFullVersion",
      "instanceMessages",
      "discoveryEndpoint",
      "maintenancePolicy",
      "maintenanceSchedule",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .authorizedNetwork) {
      self.authorizedNetwork = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .zones) {
      self.zones = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
      self.nodeCount = value
    }
    self.nodeConfig = try container.decodeIfPresent(Instance.NodeConfig.self, forKey: .nodeConfig)
    if let value = try container.decodeIfPresent(MemcacheVersion.self, forKey: .memcacheVersion) {
      self.memcacheVersion = value
    }
    self.parameters = try container.decodeIfPresent(MemcacheParameters.self, forKey: .parameters)
    if let value = try container.decodeIfPresent([Instance.Node].self, forKey: .memcacheNodes) {
      self.memcacheNodes = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .memcacheFullVersion) {
      self.memcacheFullVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Instance.InstanceMessage].self, forKey: .instanceMessages)
    {
      self.instanceMessages = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .discoveryEndpoint) {
      self.discoveryEndpoint = value
    }
    self.maintenancePolicy = try container.decodeIfPresent(
      MaintenancePolicy.self, forKey: .maintenancePolicy)
    self.maintenanceSchedule = try container.decodeIfPresent(
      MaintenanceSchedule.self, forKey: .maintenanceSchedule)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.authorizedNetwork, forKey: .authorizedNetwork)
    try container.encode(self.zones, forKey: .zones)
    try container.encode(self.nodeCount, forKey: .nodeCount)
    try container.encodeIfPresent(self.nodeConfig, forKey: .nodeConfig)
    try container.encode(self.memcacheVersion, forKey: .memcacheVersion)
    try container.encodeIfPresent(self.parameters, forKey: .parameters)
    try container.encode(self.memcacheNodes, forKey: .memcacheNodes)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.memcacheFullVersion, forKey: .memcacheFullVersion)
    try container.encode(self.instanceMessages, forKey: .instanceMessages)
    try container.encode(self.discoveryEndpoint, forKey: .discoveryEndpoint)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encodeIfPresent(self.maintenanceSchedule, forKey: .maintenanceSchedule)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for a Memcached Node.
  public struct NodeConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Number of cpus per Memcached node.
    public var cpuCount: Swift.Int32 = Swift.Int32()

    /// Required. Memory size in MiB for each Memcached node.
    public var memorySizeMb: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeConfig().with { $0.cpuCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpuCount = CodingKeys(stringValue: "cpuCount")
      static let memorySizeMb = CodingKeys(stringValue: "memorySizeMb")

      static let _knownKeys: Set<Swift.String> = [
        "cpuCount",
        "memorySizeMb",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cpuCount) {
        self.cpuCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memorySizeMb) {
        self.memorySizeMb = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpuCount, forKey: .cpuCount)
      try container.encode(self.memorySizeMb, forKey: .memorySizeMb)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.NodeConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct Node: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Identifier of the Memcached node. The node id does not
    /// include project or location like the Memcached instance name.
    public var nodeId: Swift.String = Swift.String()

    /// Output only. Location (GCP Zone) for the Memcached node.
    public var zone: Swift.String = Swift.String()

    /// Output only. Current state of the Memcached node.
    public var state: Instance.Node.State = Instance.Node.State()

    /// Output only. Hostname or IP address of the Memcached node used by the
    /// clients to connect to the Memcached server on this node.
    public var host: Swift.String = Swift.String()

    /// Output only. The port number of the Memcached server on this node.
    public var port: Swift.Int32 = Swift.Int32()

    /// User defined parameters currently applied to the node.
    public var parameters: MemcacheParameters? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Node`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Node().with { $0.nodeId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nodeId = CodingKeys(stringValue: "nodeId")
      static let zone = CodingKeys(stringValue: "zone")
      static let state = CodingKeys(stringValue: "state")
      static let host = CodingKeys(stringValue: "host")
      static let port = CodingKeys(stringValue: "port")
      static let parameters = CodingKeys(stringValue: "parameters")

      static let _knownKeys: Set<Swift.String> = [
        "nodeId",
        "zone",
        "state",
        "host",
        "port",
        "parameters",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeId) {
        self.nodeId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
        self.zone = value
      }
      if let value = try container.decodeIfPresent(Instance.Node.State.self, forKey: .state) {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
        self.host = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
        self.port = value
      }
      self.parameters = try container.decodeIfPresent(MemcacheParameters.self, forKey: .parameters)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nodeId, forKey: .nodeId)
      try container.encode(self.zone, forKey: .zone)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.host, forKey: .host)
      try container.encode(self.port, forKey: .port)
      try container.encodeIfPresent(self.parameters, forKey: .parameters)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Different states of a Memcached node.
    public enum State: Codable, Equatable, Sendable {
      /// Node state is not set.
      case unspecified
      /// Node is being created.
      case creating
      /// Node has been created and ready to be used.
      case ready
      /// Node is being deleted.
      case deleting
      /// Node is being updated.
      case updating
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .creating: return 1
        case .ready: return 2
        case .deleting: return 3
        case .updating: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .creating: return "CREATING"
        case .ready: return "READY"
        case .deleting: return "DELETING"
        case .updating: return "UPDATING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "CREATING": self = .creating
        case "READY": self = .ready
        case "DELETING": self = .deleting
        case "UPDATING": self = .updating
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .creating
        case 2: self = .ready
        case 3: self = .deleting
        case 4: self = .updating
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .creating: return try container.encode("CREATING")
        case .ready: return try container.encode("READY")
        case .deleting: return try container.encode("DELETING")
        case .updating: return try container.encode("UPDATING")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.Node"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct InstanceMessage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A code that correspond to one type of user-facing message.
    public var code: Instance.InstanceMessage.Code = Instance.InstanceMessage.Code()

    /// Message on memcached instance which will be exposed to users.
    public var message: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceMessage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceMessage().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let code = CodingKeys(stringValue: "code")
      static let message = CodingKeys(stringValue: "message")

      static let _knownKeys: Set<Swift.String> = [
        "code",
        "message",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Instance.InstanceMessage.Code.self, forKey: .code)
      {
        self.code = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
        self.message = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.code, forKey: .code)
      try container.encode(self.message, forKey: .message)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum Code: Codable, Equatable, Sendable {
      /// Message Code not set.
      case unspecified
      /// Memcached nodes are distributed unevenly.
      case zoneDistributionUnbalanced
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .zoneDistributionUnbalanced: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CODE_UNSPECIFIED"
        case .zoneDistributionUnbalanced: return "ZONE_DISTRIBUTION_UNBALANCED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CODE_UNSPECIFIED": self = .unspecified
        case "ZONE_DISTRIBUTION_UNBALANCED": self = .zoneDistributionUnbalanced
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .zoneDistributionUnbalanced
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CODE_UNSPECIFIED")
        case .zoneDistributionUnbalanced:
          return try container.encode("ZONE_DISTRIBUTION_UNBALANCED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.InstanceMessage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Different states of a Memcached instance.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// Memcached instance is being created.
    case creating
    /// Memcached instance has been created and ready to be used.
    case ready
    /// Memcached instance is updating configuration such as maintenance policy
    /// and schedule.
    case updating
    /// Memcached instance is being deleted.
    case deleting
    /// Memcached instance is going through maintenance, e.g. data plane rollout.
    case performingMaintenance
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 4
      case .performingMaintenance: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .performingMaintenance: return "PERFORMING_MAINTENANCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "PERFORMING_MAINTENANCE": self = .performingMaintenance
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .performingMaintenance
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .ready: return try container.encode("READY")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .performingMaintenance: return try container.encode("PERFORMING_MAINTENANCE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memcache.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
