// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Memorystore for Memcached instance
public struct Instance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Unique name of the resource in this scope including project and
  /// location using the form:
  ///     `projects/{project_id}/locations/{location_id}/instances/{instance_id}`
  ///
  /// Note: Memcached instances are managed and addressed at the regional level
  /// so `location_id` here refers to a Google Cloud region; however, users may
  /// choose which zones Memcached nodes should be provisioned in within an
  /// instance. Refer to [zones][google.cloud.memcache.v1.Instance.zones] field for more details.
  ///
  /// [google.cloud.memcache.v1.Instance.zones]: <doc:Instance/zones>
  public var name: Swift.String = Swift.String()

  /// User provided name for the instance, which is only used for display
  /// purposes. Cannot be more than 80 characters.
  public var displayName: Swift.String = Swift.String()

  /// Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// The full name of the Google Compute Engine
  /// [network](/compute/docs/networks-and-firewalls#networks) to which the
  /// instance is connected. If left unspecified, the `default` network
  /// will be used.
  public var authorizedNetwork: Swift.String = Swift.String()

  /// Zones in which Memcached nodes should be provisioned.
  /// Memcached nodes will be equally distributed across these zones. If not
  /// provided, the service will by default create nodes in all zones in the
  /// region for the instance.
  public var zones: [Swift.String] = []

  /// Required. Number of nodes in the Memcached instance.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Required. Configuration for Memcached nodes.
  public var nodeConfig: Instance.NodeConfig? = nil

  /// The major version of Memcached software.
  /// If not provided, latest supported version will be used. Currently the
  /// latest supported major version is `MEMCACHE_1_5`.
  /// The minor version will be automatically determined by our system based on
  /// the latest supported minor version.
  public var memcacheVersion: MemcacheVersion = MemcacheVersion()

  /// User defined parameters to apply to the memcached process
  /// on each node.
  public var parameters: MemcacheParameters? = nil

  /// Output only. List of Memcached nodes.
  /// Refer to [Node][google.cloud.memcache.v1.Instance.Node] message for more details.
  ///
  /// [google.cloud.memcache.v1.Instance.Node]: <doc:Instance/Node>
  public var memcacheNodes: [Instance.Node] = []

  /// Output only. The time the instance was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time the instance was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The state of this Memcached instance.
  public var state: Instance.State = Instance.State()

  /// Output only. The full version of memcached server running on this instance.
  /// System automatically determines the full memcached version for an instance
  /// based on the input MemcacheVersion.
  /// The full version format will be "memcached-1.5.16".
  public var memcacheFullVersion: Swift.String = Swift.String()

  /// List of messages that describe the current state of the Memcached instance.
  public var instanceMessages: [Instance.InstanceMessage] = []

  /// Output only. Endpoint for the Discovery API.
  public var discoveryEndpoint: Swift.String = Swift.String()

  /// The maintenance policy for the instance. If not provided,
  /// the maintenance event will be performed based on Memorystore
  /// internal rollout schedule.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. Published maintenance schedule.
  public var maintenanceSchedule: MaintenanceSchedule? = nil

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Configuration for a Memcached Node.
  public struct NodeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Number of cpus per Memcached node.
    public var cpuCount: Swift.Int32 = Swift.Int32()

    /// Required. Memory size in MiB for each Memcached node.
    public var memorySizeMb: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `NodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeConfig().with { $0.cpuCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.NodeConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public struct Node: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. Identifier of the Memcached node. The node id does not
    /// include project or location like the Memcached instance name.
    public var nodeId: Swift.String = Swift.String()

    /// Output only. Location (GCP Zone) for the Memcached node.
    public var zone: Swift.String = Swift.String()

    /// Output only. Current state of the Memcached node.
    public var state: Instance.Node.State = Instance.Node.State()

    /// Output only. Hostname or IP address of the Memcached node used by the
    /// clients to connect to the Memcached server on this node.
    public var host: Swift.String = Swift.String()

    /// Output only. The port number of the Memcached server on this node.
    public var port: Swift.Int32 = Swift.Int32()

    /// User defined parameters currently applied to the node.
    public var parameters: MemcacheParameters? = nil

    /// Initialize a new instance of `Node`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Node().with { $0.nodeId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Different states of a Memcached node.
    public enum State: Codable, Equatable, Sendable {
      /// Node state is not set.
      case unspecified
      /// Node is being created.
      case creating
      /// Node has been created and ready to be used.
      case ready
      /// Node is being deleted.
      case deleting
      /// Node is being updated.
      case updating
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .creating: return 1
        case .ready: return 2
        case .deleting: return 3
        case .updating: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .creating: return "CREATING"
        case .ready: return "READY"
        case .deleting: return "DELETING"
        case .updating: return "UPDATING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "CREATING": self = .creating
        case "READY": self = .ready
        case "DELETING": self = .deleting
        case "UPDATING": self = .updating
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .creating
        case 2: self = .ready
        case 3: self = .deleting
        case 4: self = .updating
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .creating: return try container.encode(1)
        case .ready: return try container.encode(2)
        case .deleting: return try container.encode(3)
        case .updating: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.Node"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public struct InstanceMessage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A code that correspond to one type of user-facing message.
    public var code: Instance.InstanceMessage.Code = Instance.InstanceMessage.Code()

    /// Message on memcached instance which will be exposed to users.
    public var message: Swift.String = Swift.String()

    /// Initialize a new instance of `InstanceMessage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceMessage().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public enum Code: Codable, Equatable, Sendable {
      /// Message Code not set.
      case unspecified
      /// Memcached nodes are distributed unevenly.
      case zoneDistributionUnbalanced
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .zoneDistributionUnbalanced: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CODE_UNSPECIFIED"
        case .zoneDistributionUnbalanced: return "ZONE_DISTRIBUTION_UNBALANCED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CODE_UNSPECIFIED": self = .unspecified
        case "ZONE_DISTRIBUTION_UNBALANCED": self = .zoneDistributionUnbalanced
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .zoneDistributionUnbalanced
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .zoneDistributionUnbalanced: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.memcache.v1.Instance.InstanceMessage"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Different states of a Memcached instance.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// Memcached instance is being created.
    case creating
    /// Memcached instance has been created and ready to be used.
    case ready
    /// Memcached instance is updating configuration such as maintenance policy
    /// and schedule.
    case updating
    /// Memcached instance is being deleted.
    case deleting
    /// Memcached instance is going through maintenance, e.g. data plane rollout.
    case performingMaintenance
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 4
      case .performingMaintenance: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .performingMaintenance: return "PERFORMING_MAINTENANCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "PERFORMING_MAINTENANCE": self = .performingMaintenance
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .performingMaintenance
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .performingMaintenance: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memcache.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
